version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      github-actions-updates:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/example-credential-issuer"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      gradle-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/example-credential-issuer"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      docker-updates:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/document-signing-certificate-issuer"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      npm-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/document-builder"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    cooldown:
      default-days: 7
    labels:
      - dependencies
    ignore:
      - dependency-name: "jose"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: "openid-client"
        update-types: [ "version-update:semver-major" ]
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      npm-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/document-builder"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    cooldown:
      default-days: 7
    labels:
      - dependencies
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: chore
    groups:
      docker-updates:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/platform-ca/utils"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      npm-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/test-harness"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    ignore:
      - dependency-name: "jose"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      npm-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/test-harness"
    cooldown:
      default-days: 7
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: chore
    groups:
      docker-updates:
        patterns:
          - "*"