repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint
        language: unsupported
        pass_filenames: false
        stages: [pre-commit]

      - id: prettier
        name: prettier
        entry: npm run format:check
        language: unsupported
        pass_filenames: false
        stages: [pre-commit]

      - id: typecheck
        name: typecheck
        entry: npm run typecheck
        language: unsupported
        stages: [pre-commit]
        pass_filenames: false

      - id: test
        name: test
        entry: npm test
        language: unsupported
        stages: [pre-push]
        pass_filenames: false
