name: Mdoc Builder - Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code-quality-and-security-analysis:
    name: Run code quality and security analysis
    if: github.triggering_actor != 'dependabot[bot]'
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  typecheck-lint-format:
    name: Typecheck, Lint and format
    uses: ./.github/workflows/typecheck-lint-format.yaml

  build-and-component-tests:
    name: Build and component tests
    uses: ./.github/workflows/build-and-component-tests.yaml

  conventional-commits:
    name: Conventional commits
    uses: ./.github/workflows/conventional-commits.yaml
