name: Mdoc Builder - Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-code-quality-and-security-analysis:
    name: Run code quality and security analysis
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/sonarqube.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  lint-and-format:
    name: Lint and format
    uses: ./.github/workflows/lint-and-format.yaml
